### ISSUE TITLE
No plugin found for anc-maven-plugin

### ISSUE THREAD

**Issue by marcverhagen** [oanc/org.anc.lapps.datasource.generic#2]
The code in GenericDatasource.java depends on a Version class which allegedly is generated by

```
mvn anc-maven-plugin:version
mvn anc-maven-plugin:version-class
```

Is that correct? When I do that I get an error:

```
[ERROR] No plugin found for prefix 'anc-maven-plugin' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/marc/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
```

For now I just replaced Version.getVersion() with a string.

**Comment by ksuderman** [comment]
That will work, and that Version class will be replaced the next time the project is built.

You can also generate the Version class with:

```
mvn generate-resources
-or-
mvn compile
-or-
mvn anc:version
```
